# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tie-Array-Packed-Auto
version:      0.03
version_from: lib/Tie/Array/Packed/Auto.pm
installdirs:  site
requires:
    Tie::Array::PackedC:           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
